# Generated by Django 3.2.18 on 2023-05-12 04:53

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_release_date_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=1, upload_to=movies.models.Movie.image_path),
            preserve_default=False,
        ),
    ]
