# Generated by Django 3.2.18 on 2023-05-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviepeople',
            old_name='Character_name',
            new_name='character_name',
        ),
        migrations.RenameField(
            model_name='moviepeople',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
