# Generated by Django 3.2.18 on 2023-05-20 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import magazines.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgzn_title', models.CharField(blank=True, max_length=50, null=True)),
                ('cover', models.ImageField(upload_to=magazines.models.Magazine.image_path)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('official', models.URLField(blank=True, null=True)),
                ('where_to_buy', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MagazineMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazines.magazine')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
