# Generated by Django 3.2.18 on 2023-05-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='official',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='where_to_buy',
            field=models.URLField(blank=True, null=True),
        ),
    ]
