# Generated by Django 3.2.18 on 2023-05-15 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_auto_20230515_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinemovie',
            name='magazine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magazines.magazine'),
            preserve_default=False,
        ),
    ]
