# Generated by Django 3.2.18 on 2023-05-12 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('original_title', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('release_Date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('드라마', '드라마'), ('판타지', '판타지'), ('서부', '서부'), ('공포', '공포'), ('로맨스', '로맨스'), ('모험', '모험'), ('스릴러', '스릴러'), ('느와르', '느와르'), ('컬트', '컬트'), ('다큐멘터리', '다큐멘터리'), ('코미디', '코미디'), ('가족', '가족'), ('미스터리', '미스터리'), ('전쟁', '전쟁'), ('애니메이션', '애니메이션'), ('범죄', '범죄'), ('뮤지컬', '뮤지컬'), ('SF', 'SF'), ('액션', '액션'), ('무협', '무협'), ('에로', '에로'), ('서스펜스', '서스펜스'), ('서사', '서사'), ('블랙코미디', '블랙코미디'), ('실험', '실험'), ('영화카툰', '영화카툰'), ('영화음악', '영화음악'), ('영화패러디포스터', '영화패러디포스터')], max_length=50, null=True)),
                ('country', models.CharField(blank=True, choices=[('프랑스', '프랑스'), ('영국', '영국'), ('홍콩', '홍콩'), ('일본', '일본'), ('한국', '한국'), ('미국', '미국'), ('기타', '기타')], max_length=50, null=True)),
                ('running_time', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish_users', models.ManyToManyField(related_name='wish_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoviePeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=50, null=True)),
                ('part', models.CharField(blank=True, max_length=50, null=True)),
                ('Character_name', models.CharField(blank=True, max_length=50, null=True)),
                ('person_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
