# Generated by Django 3.2.18 on 2023-05-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_user_id_movie_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_Date',
            new_name='release_date',
        ),
    ]
